use std::{
    env, fs,
    path::{Path, PathBuf},
    process::Command,
    time::{SystemTime, UNIX_EPOCH},
};

use crate::{git, nix};

pub struct CommitOptions {
    pub commit: bool,
    pub signed: bool,
    pub signing_key: Option<String>,
    pub gpg_format: Option<String>,
}

pub fn dry_run_package(root: &Path, package: &str) -> Result<(), String> {
    println!("\n==> {package}");
    let worktree = TempWorktree::create(root)?;
    run_update_script(worktree.path(), package)?;

    if git::clean(worktree.path())? {
        println!("No changes.");
        return Ok(());
    }

    println!("--- diffstat ---");
    print!("{}", git::diff_stat(worktree.path())?);
    println!("--- diff ---");
    print!("{}", git::diff(worktree.path())?);
    Ok(())
}

pub fn update_package(root: &Path, package: &str, commit: CommitOptions) -> Result<(), String> {
    let old_version = nix::package_version(root, package).unwrap_or_else(|_| "unknown".to_string());
    run_update_script(root, package)?;

    if git::clean(root)? {
        println!("No diff after running update script.");
        return Ok(());
    }

    let new_version = nix::package_version(root, package).unwrap_or_else(|_| "unknown".to_string());
    let (title, body) = pr_text(package, &old_version, &new_version);

    println!("\n--- suggested PR title ---\n{title}");
    println!("\n--- suggested PR body ---\n{body}");
    println!("\n--- diffstat ---");
    print!("{}", git::diff_stat(root)?);

    println!("\n--- build ---");
    if !nix::build_package(root, package)? {
        return Err("build failed; leaving changes in working tree".to_string());
    }

    if commit.commit {
        if let Some(format) = commit.gpg_format.as_deref() {
            git::run(root, &["config", "gpg.format", format])?;
        }
        if let Some(key) = commit.signing_key.as_deref() {
            git::run(root, &["config", "user.signingkey", key])?;
        }
        git::commit(root, &title, &body, commit.signed)?;
        println!("Committed{}: {title}", if commit.signed { " signed" } else { "" });
    } else {
        println!("\nNo commit created. Re-run with --commit to commit, or --commit --signed for a signed commit.");
    }

    Ok(())
}

pub fn run_update_script_cmd(args: &[String]) -> Result<(), String> {
    let mut package = None;
    let mut root = env::current_dir().map_err(|e| format!("current dir: {e}"))?;
    let mut i = 0;
    while i < args.len() {
        match args[i].as_str() {
            "--package" | "-p" => {
                i += 1;
                package = args.get(i).cloned();
            }
            "--root" | "-C" => {
                i += 1;
                root = PathBuf::from(args.get(i).ok_or("missing value for --root")?);
            }
            other => return Err(format!("unknown run-update-script argument: {other}")),
        }
        i += 1;
    }
    let package = package.ok_or("usage: bumpkin run-update-script --package <attr> [--root <repo>]")?;
    run_update_script(&root, &package)
}

fn run_update_script(root: &Path, package: &str) -> Result<(), String> {
    println!("Running passthru.updateScript for {package}...");
    let script_out = nix::build_update_script(root, package)?;
    let script = find_executable_in_output(Path::new(&script_out))?;
    let status = Command::new(&script)
        .current_dir(root)
        .status()
        .map_err(|e| format!("run {}: {e}", script.display()))?;
    if status.success() { Ok(()) } else { Err(format!("{} exited with {status}", script.display())) }
}

fn find_executable_in_output(out: &Path) -> Result<PathBuf, String> {
    let bin = out.join("bin");
    if bin.is_dir() {
        for entry in fs::read_dir(&bin).map_err(|e| format!("read {}: {e}", bin.display()))? {
            let path = entry.map_err(|e| format!("read bin entry: {e}"))?.path();
            if path.is_file() {
                return Ok(path);
            }
        }
    }
    if out.is_file() {
        return Ok(out.to_path_buf());
    }
    Err(format!("could not find executable in {}", out.display()))
}

fn pr_text(package: &str, old_version: &str, new_version: &str) -> (String, String) {
    let title = if old_version != "unknown" && new_version != "unknown" && old_version != new_version {
        format!("{package}: {old_version} -> {new_version}")
    } else {
        format!("{package}: update")
    };
    let body = format!("Updates `{package}` from `{old_version}` to `{new_version}`.\n\nGenerated by bumpkin.");
    (title, body)
}

struct TempWorktree {
    root: PathBuf,
    original: PathBuf,
}

impl TempWorktree {
    fn create(root: &Path) -> Result<Self, String> {
        let stamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map_err(|e| format!("system time: {e}"))?
            .as_nanos();
        let temp = env::temp_dir().join(format!("bumpkin-{}-{stamp}", std::process::id()));
        git::run(root, &["worktree", "add", "--detach", temp.to_str().ok_or("non-utf8 temp path")?, "HEAD"])?;
        Ok(Self { root: temp, original: root.to_path_buf() })
    }

    fn path(&self) -> &Path {
        &self.root
    }
}

impl Drop for TempWorktree {
    fn drop(&mut self) {
        let _ = git::run(&self.original, &["worktree", "remove", "--force", self.root.to_str().unwrap_or("")]);
    }
}
